[package]
name = "zap-ext"
version = "0.5.0"
authors = ["Leandro Ostera <leandro@abstractmachines.dev>"]
description = "A simple, fast, and correct build system for modern polyglot teams"
edition = "2021"

[lib]
path = "lib.rs"
