[package]
name = "tricorder-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tricorder-core = { path = "../core", version = "*" }

tonic = "0.8.2"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "tricorder"
path = "main.rs"