[[mix_library]]
name = "kadabra"
deps = [
  "//3rdparty/hexpm/credo",
  "//3rdparty/hexpm/dialyxir",
  "//3rdparty/hexpm/dogma",
  "//3rdparty/hexpm/ex_doc",
  "//3rdparty/hexpm/excoveralls",
  "//3rdparty/hexpm/hpack"
]
