[package]
name = "crane"
version = "0.1.0"
authors = ["Leandro Ostera <leandro@ostera.io>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
fern = { version = "0.6", features = [ "colored" ] }
glob = "0.3"
log = "0.4"
petgraph = "0.5"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
toml = "0.5"
