[toolchain]
channel = "nightly-2023-04-11"
components = ["rustfmt", "clippy", "llvm-tools"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
profile = "minimal"
