[workspace]
name = "warp-build"
ignore_patterns = [
  "warp-*",
  ".terraform*",
  "3rdparty/hexpm",
  "3rdparty/tests",
  "3rdparty/rebar3",
  "3rdparty/npm",
  "node_modules",
  "target",
  "lib/bs",
  "deps",
  "_build",
  "cli",
]
use_git_hooks = true

[remote_workspaces]
"tools.warp.build" = { url = "https://github.com/warp-build/tools.warp.build/archive/refs/heads/main.zip", sha1 = "", prefix = "tools.warp.build-main" }
# "custom.tools.warp.build" = { github = "username/repo", ref = "" }

[aliases]
deno = "https://pkgs.warp.build/toolchains/deno"
elixir = "https://pkgs.warp.build/toolchains/elixir"
erlang = "https://pkgs.warp.build/toolchains/erlang"
firefly = "https://pkgs.warp.build/toolchains/firefly"
flyctl = "https://pkgs.warp.build/toolchains/flyctl"
node = "https://pkgs.warp.build/toolchains/node"
rescript = "https://pkgs.warp.build/toolchains/rescript"
terraform = "https://pkgs.warp.build/toolchains/terraform"
python = "https://pkgs.warp.build/toolchains/python"

[toolchains.firefly]
sha1 = "4f1795afef0944216f4be88798bae1523ecb8c5e"
version = "0.1.0"
release_date = "nightly-2020-09-02"

[toolchains.node]
sha1 = "7c730d659dc508ad0338dee702974250752394f7"
version = "18.9.0"

[toolchains.deno]
sha1_aarch64 = "be39f6d13c2fc45f79ebfb770a67b31d298c4e2e"
sha1_x86_64 = "ebb5f08faffef2ad3b22f6faefe9dc9d3940fa40"
version = "1.22.2"

[toolchains.elixir]
sha1 = "f3d3f78c4bb36b4aeab66ea0687f19f821c352aa"
kind = "source"
version = "1.13"

[toolchains.openssl]
sha1 = "73118336c58ece2e3b87f1f933f8ba446e2bdc26"
version = "OpenSSL_1_1_1q"

[toolchains.erlang]
sha1 = "2bb7456ccb19cf83b07506744fb540ce4d66b257"
version = "25.0"

[toolchains.flyctl]
sha1_aarch64 = "bae0f096ec524ca5a85ec401b58444108e097218"
sha1_x86_64 = "9f7a64ae5426e0101d492726416589acd0c110ab"
version = "0.0.393"

[toolchains.rebar3]
sha1 = "143d3473dae6ea8250452f7a29db73974be51b24"

[toolchains.rescript]
sha1 = "d5279f085d19a2234d2024080ad90bf69a09ab66"
version = "9.1.4"

[toolchains.terraform]
sha1_aarch64 = "14e5c4ec076c44e25593a3af95df656f649e2f33"
sha1_x86_64 = "4f91ac340f9722c5e11827e9b8b5aaf48ecc4b0e"
version = "1.2.4"

[toolchains.python]
sha1 = "eb46fce3d3b86320699a505a6dc69ce586b8f66a"
version = "3.10.7"
