[workspace]
name = "zap-cloud"

[toolchains.rescript]
archive_url = "https://github.com/rescript-lang/rescript-compiler/archive/refs/tags/9.1.4.tar.gz"
checksum = "d5279f085d19a2234d2024080ad90bf69a09ab66"
strip_prefix = "rescript-compiler-9.1.4"

[toolchains.erlang]
archive_url = "https://github.com/erlang/otp/archive/OTP-25.0.tar.gz"
checksum = "682add536cdb95f75866108affa80b880914007c"
strip_prefix = "otp-OTP-25.0"

[toolchains.elixir]
archive_url = "https://github.com/elixir-lang/elixir/archive/refs/tags/v1.13.4.tar.gz"
checksum = "d0269a1bd2e5256a1842b5b201649e9a39227bb2"
strip_prefix = "elixir-1.13.4"

[dependencies.npm]
rescript = "~> 9.1"
