[workspace]
name = "tools.warp.build"
ignore_patterns = []
use_git_hooks = true

[aliases]
erlang = "https://pkgs.warp.build/toolchains/erlang"
rebar3 = "https://pkgs.warp.build/toolchains/rebar3"

[toolchains.openssl]
sha1 = "73118336c58ece2e3b87f1f933f8ba446e2bdc26"
version = "OpenSSL_1_1_1q"

[toolchains.erlang]
sha1 = "2bb7456ccb19cf83b07506744fb540ce4d66b257"
version = "25.0"

[toolchains.rebar3]
sha1 = "143d3473dae6ea8250452f7a29db73974be51b24"

[toolchains.cmake]
sha1 = "19b1473e6ded2d234256b6aac90eb22616c5ab5e"
version = "3.24.2"

[resolvers.overrides]
"hex.pm" = "//hexpm/resolver" 
