[workspace]
name = "warp-build"
ignore_patterns = ["\\.git", "_build", "deps", "lib/bs", "target", "node_modules"]
use_git_hooks = true

[aliases]
"@fmt" = "hello_world:hello_world"
flyctl = "//warp.build/toolchains:flyctl"
terraform = "//warp.build/toolchains:terraform"
[toolchains.deno]
sha1 = "be39f6d13c2fc45f79ebfb770a67b31d298c4e2e"
version = "1.22.2"

[toolchains.elixir]
sha1 = "325fbdde4f0a5701bb8b9d455175b85ff41470d7"
version = "1.13.4"

[toolchains.erlang]
build_flags = ["-t"]
sha1 = "2bb7456ccb19cf83b07506744fb540ce4d66b257"
version = "25.0"

[toolchains.flyctl]
sha1 = "bbb83670002ed5dddbca7252e90ed9465853f7d5"
version = "0.0.344"

[toolchains.rebar3]
sha1 = "143d3473dae6ea8250452f7a29db73974be51b24"

[toolchains.rescript]
sha1 = "d5279f085d19a2234d2024080ad90bf69a09ab66"
version = "9.1.4"

[toolchains.terraform]
sha1 = "14e5c4ec076c44e25593a3af95df656f649e2f33"
version = "1.2.4"
