[workspace]
name = "warp-build"
ignore_patterns = [
  "warp-*",
  ".terraform*",
  "3rdparty/hexpm",
  "3rdparty/rebar3",
  "3rdparty/npm",
  "node_modules",
  "target",
  "lib/bs",
  "deps",
  "_build",
  "cli",
]
use_git_hooks = true

[aliases]
flyctl = "//warp.build/toolchains:flyctl"
terraform = "//warp.build/toolchains:terraform"

[toolchains.deno]
sha1 = "be39f6d13c2fc45f79ebfb770a67b31d298c4e2e"
version = "1.22.2"

[toolchains.elixir]
sha1 = "f3d3f78c4bb36b4aeab66ea0687f19f821c352aa"
kind = "source"
version = "1.13"

[toolchains.openssl]
sha1 = "73118336c58ece2e3b87f1f933f8ba446e2bdc26"
version = "OpenSSL_1_1_1q"

[toolchains.erlang]
sha1 = "2bb7456ccb19cf83b07506744fb540ce4d66b257"
version = "25.0"

[toolchains.flyctl]
sha1 = "bbb83670002ed5dddbca7252e90ed9465853f7d5"
version = "0.0.344"

[toolchains.rebar3]
sha1 = "143d3473dae6ea8250452f7a29db73974be51b24"

[toolchains.rescript]
sha1 = "d5279f085d19a2234d2024080ad90bf69a09ab66"
version = "9.1.4"

[toolchains.terraform]
sha1_aarch64 = "14e5c4ec076c44e25593a3af95df656f649e2f33"
sha1_x86_64 = "4f91ac340f9722c5e11827e9b8b5aaf48ecc4b0e"
version = "1.2.4"
