[[rebar3_library]]
name = "hackney"
deps = [
  "//3rdparty/hexpm/certifi",
  "//3rdparty/hexpm/idna",
  "//3rdparty/hexpm/metrics",
  "//3rdparty/hexpm/mimerl",
  "//3rdparty/hexpm/parse_trans",
  "//3rdparty/hexpm/ssl_verify_fun",
  "//3rdparty/hexpm/unicode_util_compat"
]
