[package]
name = "zap-build"
version = "0.5.0"
authors = ["Leandro Ostera <leandro@abstractmachines.dev>"]
description = "A simple, fast, and correct build system for modern polyglot teams"
edition = "2021"

[[bin]]
name = "zap"
path = "main.rs"

[dependencies]
zap-core = { path = "../core", version = "*" }

anyhow = "1.0"
human-panic = "1.0"
chrono = "0.4"
env_logger="0.9"
futures = "0.3"
guess_host_triple = "0.1"
log = "0.4"
structopt = "0.3"
termcolor = "1.1"
tokio = { version = "1", features = ["full"] }
crossbeam-channel = "0.4.0"
notify = "5.0.0-pre.15"

[dev-dependencies]
insta = "1.14"
assert_cmd = "2"
dir-diff = "0.3"
