[package]
name = "warp-build"
version = "0.5.0"
authors = ["Leandro Ostera <leandro@abstractmachines.dev>"]
description = "A simple, fast, and correct build system for modern polyglot teams"
edition = "2021"

[[bin]]
name = "warp"
path = "main.rs"

[dependencies]
warp-core = { path = "../core", version = "*" }

anyhow = "1.0"
chrono = "0.4"
console = "0.15"
crossbeam = "0.8"
crossbeam-channel = "0.4.0"
crossterm = "0.23"
env_logger="0.9"
futures = "0.3"
fxhash = "0.2"
guess_host_triple = "0.1"
human-panic = "1.0"
humantime = "2"
indicatif = "0.16"
notify = "5.0.0-pre.15"
num_cpus = "1"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"]  }
structopt = "0.3"
termcolor = "1.1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
tracing-opentelemetry = "0.17"
tracing-subscriber = "0.3"

[dev-dependencies]
insta = "1.14"
assert_cmd = "2"
dir-diff = "0.3"
