[package]
name = "tricoder"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8.2"
tokio = { version = "1", features = ["full"] }
prost = "0.11.2"

[lib]
path = "src/lib.rs"

[build-dependencies]
tonic-build = "0.8.2"
