---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: [23.0, 24.0, 25.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 efmt -c
      - run: rebar3 eunit
      - run: rebar3 dialyzer
      - run: rebar3 edoc
  cov:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 eunit
      - run: rebar3 cover
      - run: rebar3 covertool generate
      - run: cp _build/test/covertool/jsone.covertool.xml ./cobertura.xml
      - run: sudo pip install codecov
      - run: codecov
