[[mix_library]]
name = "makeup"
srcs = [
  "lib/**/*.js",
      "lib/**/*.eex",
      "lib/**/*.ex",
      "mix.exs",
      "src/**/*.app.src",
      "src/**/*.erl",
      "src/**/*.hrl",
      "include/**/*.hrl",
      "priv/**/*",
    ]
deps = [
  "//3rdparty/hexpm/nimble_parsec"
]
