[[mix_library]]
name = "benchee"
deps = [
  "//3rdparty/hexpm/credo",
  "//3rdparty/hexpm/deep_merge",
  "//3rdparty/hexpm/dialyxir",
  "//3rdparty/hexpm/ex_doc",
  "//3rdparty/hexpm/ex_guard",
  "//3rdparty/hexpm/excoveralls",
  "//3rdparty/hexpm/inch_ex",
  "//3rdparty/hexpm/statistex"
]
