[[mix_library]]
name = "benchee_json"
deps = [
  "//3rdparty/hexpm/benchee",
  "//3rdparty/hexpm/credo",
  "//3rdparty/hexpm/dialyxir",
  "//3rdparty/hexpm/earmark",
  "//3rdparty/hexpm/ex_doc",
  "//3rdparty/hexpm/excoveralls",
  "//3rdparty/hexpm/jason"
]
