[[elixir_library]]
name = "lib"
deps = [
  "//zap/dsc/shared_cache"
]

[[elixir_application]]
name = "app"
app_name = "zap_dsc"
mod = "Zap.Dsc.Application"
apps = [ "kernel", "stdlib" ]
deps = [ ":lib" ]
