[[mix_library]]
name = "benchee_html"
deps = [
  "//3rdparty/hexpm/benchee",
  "//3rdparty/hexpm/benchee_json",
  "//3rdparty/hexpm/credo",
  "//3rdparty/hexpm/dialyxir",
  "//3rdparty/hexpm/earmark",
  "//3rdparty/hexpm/ex_doc",
  "//3rdparty/hexpm/excoveralls",
  "//3rdparty/hexpm/mix_test_watch"
]
