name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.13-slim   # otp 24
          - 1.12-slim   # otp 24
          - 1.11-slim   # otp 23
          - 1.10-slim   # otp 22
          - 1.9-slim    # otp 22
          - 1.8-otp-22
          - 1.8-slim    # otp 21
          - 1.7-slim    # otp 21
    container:
      image: elixir:${{ matrix.elixir }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test --trace

  test-1:
    name: run tests from v1.0.0
    runs-on: ubuntu-latest
    container:
      image: elixir:1.7-slim
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Checkout v1.0.0 tests
      uses: actions/checkout@v2
      with:
        path: "test-1"
        ref: "v1.0.0-compat"

    - name: Replace test dir with test-1/test dir
      run: |
        ls -la
        rm -rf test
        mv test-1/test test

    - name: Run v1.0.0 Tests
      run: mix test --trace

  test-poison3:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-slim
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        MIX_ENV: test
        LOCKFILE: poison3
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests for poison 3.x
      env:
        MIX_ENV: test
        LOCKFILE: poison3
      run: mix test --trace

  format:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-slim
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Format
      run: mix format --check-formatted --dry-run
