[dependencies]
makeup = {
  version = "~> 0.9"
  overrides = {
    rule = "mix_library",
    deps = [
      "//ex_doc",
    ]
  }
}
ex_doc = {
  version = "~> 0.9"
  overrides = {
    rule = "mix_library",
    deps = [
      "//makeup_erlang",
    ]
  }
}
makeup_erlang = {
  version = "~> 0.9"
  overrides = {
    rule = "mix_library",
    deps = [
      "//makeup_html",
    ]
  }
}
