[dependencies]
benchee = { version = ">= 0.99.0 and < 2.0.0" }
benchee_json = { version = "~> 1.0" }
bunt = { version = "~> 0.2" }
certifi = { version = "~>2.9.0" }
cowboy = { version = "~> 2.7" }
cowboy_telemetry = { version = "~> 0.3" }
decimal = { version = "~> 1.6 or ~> 2.0" }
deep_merge = { version = "~> 1.0" }
earmark_parser = { version = "~> 1.4.25" }
erlex = { version = ">= 0.2.6" }
ex_aws = { version = "~> 2.0" }
fs = { version = "~> 6.9" }
hackney = { version = "~> 1.16" }
hpack = { version = "3.0.1" }
ibrowse = { version = "== 4.4.0" }
idna = { version = "~>6.1.0" }
jason = { version = "1.3.0" }
joken = { version = "2.4.1" }
jsx = { version = "~> 2.8.0" }
makeup_elixir = { version = "~> 0.14" }
makeup_erlang = { version = "~> 0.1" }
meck = { version = "~> 0.9" }
metrics = { version = "~>1.0.0" }
mime = { version = "~> 1.2 or ~> 2.0" }
mimerl = { version = "~>1.1" }
parse_trans = { version = "3.3.1" }
plug = { version = "1.13.6" }
plug_cowboy = { version = "2.5.2" }
plug_crypto = { version = "~> 1.1.1 or ~> 1.2" }
poison = { version = ">= 2.0.0" }
ssl_verify_fun = { version = "~>1.1.0" }
statistex = { version = "~> 1.0" }
telemetry = { version = "~> 0.4 or ~> 1.0" }
tesla = { version = "1.4.4" }
unicode_util_compat = { version = "~>0.7.0" }
uuid = { version = "1.1.8" }

[dependencies.cowlib]
github = "ninenines/cowlib"
options = [{ github = "ninenines/cowlib" }]

[dependencies.ex_aws_s3]
overrides = { extra_srcs = ["README.md"] }
version = "2.3.2"

[dependencies.file_system]
overrides = { extra_srcs = ["README.md"] }
version = "0.2.10"

[dependencies.hoedown]
github = "hoedown/hoedown"
options = [
  { github = "hoedown/hoedown" },
  { app = false }
]

[dependencies.hpax]
overrides = { extra_srcs = ["lib/hpax/huffman_table"] }
version = "0.1.1"

[dependencies.html_entities]
overrides = { extra_srcs = ["lib/*.txt"] }
version = "0.5.2"

[dependencies.jose]
overrides = {extra_srcs = ["include/*.hrl"],  modules = [
  "JOSE",
  "JOSE.JWA",
  "JOSE.JWE",
  "JOSE.JWK",
  "JOSE.JWS",
  "JOSE.JWT"
]}
version = "1.11.2"

[dependencies.makeup]
overrides = { extra_srcs = ["lib/**/*.js"] }
version = "1.1.0"

[dependencies.nimble_parsec]
overrides = { extra_srcs = ["README.md"] }
version = "1.2.3"

[dependencies.ranch]
github = "ninenines/ranch"
options = [{ github = "ninenines/ranch" }]

[dependencies.unicode]
overrides = { extra_srcs = ["data/*.txt"] }
version = "1.13.1"
