[dependencies]
assert_value = { version = "~> 0.9" }
benchee = { version = ">= 0.99.0 and < 2.0.0" }
benchee_html = { version = "~> 1.0" }
benchee_json = { version = "~> 1.0" }
benchee_markdown = { version = "~> 0.2" }
benchfella = { version = "~> 0.3" }
bunt = { version = "~> 0.2.0" }
bypass = { version = "~> 2.1" }
certifi = { version = "~>2.9.0" }
cowboy = { version = "~> 2.7" }
cowboy_telemetry = { version = "~> 0.3" }
cowlib = { github = "ninenines/cowlib" }
decimal = { version = "~> 1.6 or ~> 2.0" }
deep_merge = { version = "~> 1.0" }
dialyxir = { version = "~> 1.0" }
dialyzex = { version = "~> 1.2" }
dogma = { version = "~> 0.1" }
earmark = { version = "~> 1.2" }
earmark_ast_dsl = { version = "~> 0.3.6" }
earmark_parser = { version = "~> 1.4.25" }
ecto = { version = "3.8.3" }
erlex = { version = ">= 0.2.6" }
espec = { version = "~> 1.6" }
ex_aws = { version = "~> 2.0" }
ex_doc = { version = ">= 0.0.0" }
ex_guard = { version = "~> 1.3" }
excoveralls = { version = "~> 0.13" }
exjsx = { version = "~> 4.0" }
extractly = { version = "~> 0.5.3" }
floki = { version = "~> 0.21" }
fs = { version = "~> 6.9" }
hackney = { version = ">= 0.0.0" }
hoedown = { github = "hoedown/hoedown" }
hpack = { version = ">= 0.0.0" }
httpotion = { version = "~> 3.1" }
ibrowse = { version = "== 4.4.0" }
idna = { version = "~>6.1.0" }
inch_ex = { version = "~> 2.0" }
jason = { version = "~> 1.0" }
jiffy = { version = "~> 1.0" }
joken = { version = ">= 0.0.0" }
json = { version = "~> 1.4" }
jsone = { version = "~> 1.6" }
jsx = { version = "~> 2.8.0" }
junit_formatter = { version = "~> 3.3" }
kadabra = { version = "0.3.4" }
makeup_elixir = { version = "~> 0.14" }
makeup_erlang = { version = "~> 0.1" }
makeup_html = { version = ">= 0.0.0" }
markdown = { github = "devinus/markdown" }
meck = { version = "~> 0.9" }
metrics = { version = "~>1.0.0" }
mime = { version = "~> 1.2 or ~> 2.0" }
mimerl = { version = "~>1.1" }
mint = { version = "~> 1.1" }
mix_test_watch = { version = "~> 0.2" }
mixunit = { version = "~> 0.9.2" }
mock = { version = "~> 0.3.6" }
mox = { version = "~> 1.0" }
parse_trans = { version = "3.3.1" }
plug = { version = "~> 1.7" }
plug_cowboy = { version = "~> 2.0" }
plug_crypto = { version = "~> 1.1.1 or ~> 1.2" }
ranch = { version = "~> 1.3" }
ssl_verify_fun = { version = "~>1.1.0" }
statistex = { version = "~> 1.0" }
stream_data = { version = "~> 0.5.0" }
sweet_xml = { version = "~> 0.7" }
telemetry = { version = "~> 0.4 or ~> 1.0" }
temp = { version = "~> 0.4" }
temporary_env = { version = "~> 1.0" }
tiny = { version = "~> 1.0" }
traverse = { version = "~> 1.0.1" }
unicode_set = { version = "~> 1.1.0" }
unicode_util_compat = { version = "~>0.7.0" }
uuid = { version = "1.1.8" }
x509 = { version = "~> 0.6.0" }

[dependencies.credo]
overrides = { extra_srcs = [
  ".*.ex",
  ".*.html"
] }
version = "~> 1.6"

[dependencies.ex_aws_s3]
overrides = { extra_srcs = ["README.md"] }
version = "2.3.1"

[dependencies.file_system]
overrides = { extra_srcs = ["README.md"] }
version = "~> 0.2.8"

[dependencies.hpax]
overrides = { extra_srcs = ["lib/hpax/huffman_table"] }
version = "~> 0.1.1"

[dependencies.html_entities]
overrides = { extra_srcs = ["lib/*.txt"] }
version = "~> 0.5.0"

[dependencies.jose]
overrides = {extra_srcs = ["include/*.hrl"],  modules = [
  "JOSE",
  "JOSE.JWA",
  "JOSE.JWE",
  "JOSE.JWK",
  "JOSE.JWS",
  "JOSE.JWT"
]}
version = "~> 1.11.2"

[dependencies.makeup]
overrides = { extra_srcs = ["lib/**/*.js"] }
version = "~> 1.0"

[dependencies.nimble_parsec]
overrides = { extra_srcs = ["README.md"] }
version = "~> 1.2.2 or ~> 1.3"

[dependencies.poison]
overrides = {extra_srcs = [
  "README.md",
  "VERSION"
],  skip_deps = "true"}
version = ">= 2.0.0"

[dependencies.unicode]
overrides = { extra_srcs = ["data/*.txt"] }
version = "~> 1.13"
