name: Fallback Release Workflow

on:
  - push
  - pull_request

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}

    steps:
      - name: Create draft release on tags
        id: create_draft_release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    needs: create_draft_release

    strategy:
      fail-fast: false
      matrix:
        include:
          # macos targets
          - target: x86_64-apple-darwin
            os: macos-latest
            rust_toolchain: stable
            deno_toolchain: "v1.25"
            otp_version: "25.3"
            elixir_version: "1.14"
            rebar3_version: "3.14.1"

          - target: aarch64-apple-darwin
            os: macos-latest
            rust_toolchain: stable
            deno_toolchain: "v1.25"
            otp_version: "25.3"
            elixir_version: "1.14"
            rebar3_version: "3.14.1"

          # linux builds
          - target: aarch64-unknown-linux-gnu
            os: buildjet-2vcpu-ubuntu-2204-arm
            rust_toolchain: stable
            deno_toolchain: "v1.25"
            otp_version: "25.3"
            elixir_version: "1.14"
            rebar3_version: "3.14.1"

          - target: aarch64-unknown-linux-musl
            os: buildjet-2vcpu-ubuntu-2204-arm
            rust_toolchain: stable
            deno_toolchain: "v1.25"
            otp_version: "25.3"
            elixir_version: "1.14"
            rebar3_version: "3.14.1"

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            rust_toolchain: stable
            deno_toolchain: "v1.25"
            otp_version: "25.3"
            elixir_version: "1.14"
            rebar3_version: "3.14.1"

    env:
      OS: ${{ matrix.os }}
      RUST_TOOLCHAIN: ${{ matrix.rust_toolchain }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch tags
        id: tag
        run: git fetch --tags --force

      - name: Cached Infra
        uses: actions/cache@v2
        env:
          cache-name: cached-cargo
        with:
          path: |
           ~/.cargo
           target
           C:\cygwin
          key: v${{ secrets.CACHE_VERSION }}-${{ matrix.os }}-${{ matrix.target }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v${{ secrets.CACHE_VERSION }}-${{ matrix.os }}-${{ matrix.target }}-${{ env.cache-name }}-
            v${{ secrets.CACHE_VERSION }}-${{ matrix.os }}-${{ matrix.target }}-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.target }}

      - uses: ostera/setup-deno@d77d23e81419383bfcdb535d27cd6da58abb78d9
        with:
          deno-version: ${{ matrix.deno_toolchain }}

      - uses: erlef/setup-beam@v1
        if: ${{ (runner.os != 'macOS') && !matrix.target.includes("aarch64") }}
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - uses: ostera/setup-protoc@71794594049b1021c13b630661a3c873ca5f0395
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: Define env (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: echo "GITHUB_TAG=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Setup Rust targets
        run: make setup

      - name: Run code checks
        if: ${{ runner.os != 'macOS' }}
        run: make check

      - name: Build project
        run: make build

      - name: Run tests
        if: ${{ (runner.os == 'macOS') || matrix.target.includes("aarch64") }}
        run: make test.tricorder test.unit test.conc

      - name: Run tests
        if: ${{ (runner.os != 'Linux') && !matrix.target.includes("aarch64") }}
        run: make test

      - name: Create release archive (Unix)
        if: ${{ success() && runner.os != 'Windows' }}
        run: make release.ci

      - name: Upload Warp build artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          path: release.tar.gz
          name: warp-${{ env.GITHUB_TAG }}-${{ matrix.target }}.tar.gz
          if-no-files-found: error

      - name: Upload Warp release tarball
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: upload-warp-release-tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: release.tar.gz
          asset_name: warp-${{ env.GITHUB_TAG }}-${{ matrix.target }}.tar.gz
          asset_content_type: application/zip
